#! /usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin";
use PVS;

my $print_full;
if ( defined($ARGV[0]) && $ARGV[0] eq "-f" ) {
  $print_full = 1;
  shift @ARGV;
}

my ($file,$nothing) = @ARGV;
if (defined($nothing)) {
  print STDERR "Usage: $0 [-f] [FASTA_FILE]\n";
  exit(1);
}
if ( !defined($file) ) {
  $file = "-";
}
my %h = PVS::read_fasta($file);

my @keys = sort (keys %h);
if ($#keys == 0 && !$print_full ) {
  my $k = $keys[0];
  my $v = $h{$k};
  print length($v),"\n";
  exit;
}

foreach my $k ( @keys ) {
  my $v = $h{$k};
  my $l = length($v);
  if ( $k =~ /gi\|[0-9]+\|ref\|([^\|.]+)/ ) {
    $k = $1;
  }
  print "$l\t$k\n";
}
