#! /bin/bash

# swiped from https://stackoverflow.com/questions/12340846/bash-shell-script-to-find-the-closest-parent-directory-of-several-files

function common_path()
{
  lhs=$1
  rhs=$2
  path=
  OLD_IFS=$IFS; IFS=/
  for w in $rhs; do
    test "$path" = / && try="/$w" || try="$path/$w"
    case $lhs in
      $try*) ;;
      *) break ;;
    esac
    path=$try
  done
  IFS=$OLD_IFS
  echo $path
}

function usage {
    echo 1>&2 "Usage: $0 dir1 dir2 ..."
    echo 1>&2 ""
    echo 1>&2 "Find the directory that is the closest common ancestor of"
    echo 1>&2 "dir1, dir2, .... Print the path to the closest"
    echo 1>&2 "common directory, relative to \".\"."
    exit $1
}

if [ "$1" = "-h" ] ; then
    usage 0
fi
if [ -z "$1" ] ; then
    usage 1
fi

ca_dir=$(realpath "$1")
shift 1
for f in "$@" ; do
    ca_dir=$(common_path "$ca_dir" "$(realpath "$f")")
done

realpath --relative-to=. "$ca_dir"

