#! /usr/bin/env perl

use strict;
use warnings FATAL => 'all';
use Carp::Always;

use File::Basename;

# use FindBin;
# use lib "$FindBin::Bin";
# use Xyzzy;

use constant { TRUE => 1, FALSE => 0 };

my $n = <STDIN>;
chomp $n;

my @blank_entries = map { 0 } 0..($n-1);

my $table = [ @blank_entries ];
for (my $i=0; $i<$n; $i++) {
  $table->[$i] = [ @blank_entries ];
}
my $names = [ @blank_entries ];

my $i=0;
while (<STDIN>) {
  chomp;
  my ($name,@values) = split(/\t/);
  $name = basename($name,".fna",".fasta");
  $names->[$i] = $name;
  $table->[$i][$i] = 1.0;
  for (my $j=0; $j<$#values; $j++) {
    if ($values[$j] eq "NA") {
      $table->[$i][$j] = $table->[$j][$i] = 0.0;
    } else {
      $table->[$i][$j] = $table->[$j][$i] = $values[$j]/100.0;
    }
  }
  $i++;
}

print join("\t", "", $names->@*),"\n";
for (my $i=0; $i<$n; $i++) {
  print join("\t", $names->[$i], $table->[$i]->@*),"\n";
}

