#! /bin/bash

if [ -z "$REFSEEK" ] ; then
    if [ -d $HOME/scratch/referenceseeker ] ; then
	REFSEEK=$HOME/scratch/referenceseeker
    else
	echo 1>&2 REFSEEK not set
	exit 1
    fi
elif [ ! -d "$REFSEEK" ] ; then
    echo 1>&2 $REFSEEK does not exist
    exit 1
fi

function usage {
    echo 1>&2 "Usage: $0 [options] genome.fna"

    echo 1>&2 "-a ANI - ANI cutoff [0.95]"
    echo 1>&2 "-g - only run against GTDB"
    echo 1>&2 "-h - this message"
    echo 1>&2 "-r - only run against RefSeq"
    echo 1>&2 "-u - unfiltered results"

    exit "$@"
}    

while getopts 'a:ghru' opt ; do
    case "$opt" in

	a) opt_a="--ani $OPTARG" ;;
	h) opt_h=1 ;;
	g) opt_g=1 ;;
	r) opt_r=1 ;;
	u) opt_u="--unfiltered" ;;

	\?) usage 1 ;;
	*) echo 1>&2 "Can't happen" ; exit 1 ;;
    esac
done
shift $((OPTIND-1))

if [ "$opt_h" ] ; then
    usage
fi

if [ -z "$1" -o "$2" ] ; then
    usage 1
fi

if [ -z "$opt_g" -a -z "$opt_r" ] ; then
    opt_g=1
    opt_r=1
fi

rm -rf $REFSEEK/temp
mkdir -p $REFSEEK/temp/tmp

cp "$1" $REFSEEK/temp/genome.fasta

echo "${PS4}cd $REFSEEK"
cd $REFSEEK


export HOWTO_MOUNT_DIR=
export HOWTO_TMPDIR=

if [ "$opt_r" ] ; then
    echo 1>&2 '### Refseq'
    (
	set -x
	referenceseeker $opt_a $opt_u ./bacteria-refseq ./temp/genome.fasta
    )
fi

if [ "$opt_g" ] ; then
    echo 1>&2 '### GTDB'
    (
	set -x
	referenceseeker $opt_a $opt_u ./bacteria-gtdb ./temp/genome.fasta
    )
fi
