#! /bin/bash

# Compute the "coverage" of an alignment. Uses this method
#
#     coverage == (read_len*number_reads_mapped) / genome_size



FILE=$1
if [ -z "$FILE" ] ; then
    echo 1>&2 "Usage: $0 file.bam"
    echo 1>&2 "   or: $0 file.sam"
    exit 1
fi

case "$FILE" in
    *.bam) ARGS= ;;
    *.sam|*.ssam) ARGS="-S" ;;
    *)
	echo 1>&2 "Don't know what to do with $FILE"
	exit 1
esac

GENOME_SIZE=`samtools view $ARGS -H $FILE  2>/dev/null | sed -e 's/.*LN://' | profile-reduce + 0`
NUM_MAPPED=`samtools view $ARGS $FILE  2>/dev/null | cut -f1 | sort -u | wc -l`
READ_LEN=`samtools view $ARGS $FILE  2>/dev/null | cut -f 10 | head -n1 | strings-length`

perl -e 'printf("%.2f\n",($ARGV[0]*$ARGV[1])/$ARGV[2]);' $READ_LEN $NUM_MAPPED $GENOME_SIZE
